name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
